openapi: 3.0.1
info:
  title: EO API Definition
  version: v1
servers:
  - url: 'http://10.200.22.64:8080/'
    description: "EO API"
paths:
  /person/search:
    post:
      tags:
        - search person
      summary: search person
      operationId: searchPerson
      requestBody:
        description: search person payload
        required: true
        content:
          application/json:
            schema:
             $ref: "#/components/schemas/PersonSearchKey"
      responses:
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal error
        "404":
          description: "No Person records found for search parameters"
        '200':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PersonSearchResultDetails'
components:
  schemas:
    PersonSearchResult:
      type: object
      description: ""
      properties:
        firstName:
          type: string
          description: "First Name of the Person"
        lastName:
          type: string
          description: "Last Name of the Person"          
        dateOfBirth:
          type: string
          description: "Date of Birth of the Person"          
        referenceNumber:
          type: string
          description: "Reference Number of Person in EO"
        city:
          type: string
          description: "City where the Person resides"
    PersonSearchKey:
      type: object
      description: "Person Search Results"
      properties:
        firstName:
          type: string
          description: "First Name of the Person"
        lastName:
          type: string
          description: "Last Name of the Person"          
        dateOfBirth:
          type: string
          description: "Date of Birth of the Person"          
        referenceNumber:
          type: string
          description: "Reference Number of Person in EO"
    EOAPIResponse:
      type: object
      properties:
        resultInd:
          type: boolean
          description: "Indicates if the call was successful"
        message:
          type: string
          description: "Informational message about the call status"
    PersonSearchResultDetails:
      type: object
      properties:
        eoAPIResponse:
          $ref: '#/components/schemas/EOAPIResponse'          
        personSearchResultDetails:
          type: array
          items:
            $ref: '#/components/schemas/PersonSearchResult'                         